version: '2.1'

services:
  go:
    build: go
    container_name: go
    environment:
      - GOGC=1000
    ports:
      - 3001:3000
  vertx:
    build: vertx
    container_name: vertx
    ports:
      - 3002:3000
  spring:
    build: spring
    container_name: spring
    ports:
      - 3003:3000
  node_express:
    build:
      context: node
      dockerfile: Dockerfile.express
    container_name: node_express
    ports:
      - 3004:3000
  node_graalvm:
    build:
      context: node
      dockerfile: Dockerfile.graalvm
    container_name: node_graalvm
    ports:
      - 3005:3000
  node_bun:
    build:
      context: node
      dockerfile: Dockerfile.bun
    container_name: node_bun
    ports:
      - 3006:3000
  node_fastify:
    build:
      context: node
      dockerfile: Dockerfile.fastify
    container_name: node_fastify
    ports:
      - 3007:3000