version: '2.1'

services:
  go:
    build: go
    container_name: go
    environment:
      - GOGC=1000
    ports:
      - 3001:3000
  vertx:
    build: vertx
    container_name: vertx
    ports:
      - 3002:3000
  spring:
    build: spring
    container_name: spring
    ports:
      - 3003:3000
  node_express:
    build:
      context: node
      dockerfile: Dockerfile.express
    container_name: node_express
    ports:
      - 3004:3000
  # node_graalvm:
  #   build:
  #     context: node
  #     dockerfile: Dockerfile.graalvm
  #   container_name: node_graalvm
  #   ports:
  #     - 3005:3000
  node_bun:
    build:
      context: node
      dockerfile: Dockerfile.bun
    container_name: node_bun
    ports:
      - 3006:3000
  node_fastify:
    build:
      context: node
      dockerfile: Dockerfile.fastify
    container_name: node_fastify
    ports:
      - 3007:3000
  # node_hyper:
  #   build:
  #     context: node
  #     dockerfile: Dockerfile.hyper
  #   container_name: node_hyper
  #   ports:
  #     - 3008:3000
  go_fiber:
    build: go_fiber
    container_name: go_fiber
    environment:
      - GOGC=1000
    ports:
      - 3009:3000
  # node_uws:
  #   build:
  #     context: node
  #     dockerfile: Dockerfile.uws
  #   container_name: node_uws
  #   ports:
  #     - 3010:3000
  helidon:
    build:
      context: helidon
      dockerfile: Dockerfile
    container_name: helidon
    ports:
      - 3011:3000
  dotnet:
    build:
      context: dotnet
    container_name: dotnet
    ports:
      - 3012:3000
  python:
    build:
      context: python
    container_name: python
    ports:
      - 3013:3000
  rust:
    build: rust
    container_name: rust
    ports:
      - 3014:3000
  swift:
    build:
      context: swift_vapor
    container_name: swift
    ports:
      - 3015:3000
